name: Build and Deploy Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # This adds the "Run workflow" button manually

jobs:
  call-shared-workflow:
    uses: RFLundgren/automation/.github/workflows/reusable-docker-push.yml@main
    with:
      image_name: "navidrome-mood-plugin"
    secrets: inherit
